server:
    port: 8080
spring:
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./build/h2db/db/store;DB_CLOSE_DELAY=-1
        username: store
        password:
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
    liquibase:
        change-log: classpath:/db/changelog/master.xml